#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 23 09:28:48 2023

@author: speechlab
"""
import os
import requests
import sounddevice as sd
import soundfile as sf
import numpy as np
from scipy.io.wavfile import write 
from flask import *
app = Flask(__name__)


app.static_folder = 'static'

@app.route('/')
def main():
   return render_template('index.html')
@app.route('/demo.html')
def demo():
   return render_template('demo.html')

@app.route('/asr.html')
def asr():
   return render_template('asr.html')


@app.route('/contact.html')
def contact():
   return render_template('contact.html')

@app.route('/index.html')
def index():
   return render_template('index.html')


@app.route('/projects.html')
def proj():
   return render_template('projects.html')


@app.route('/activities.html')
def act():
   return render_template('activities.html')


@app.route('/members.html')
def member():
   return render_template('members.html')


@app.route('/publications.html')
def pub():
    return render_template('publications.html')

token = "baa0803e8fc3f70d643e53136316573f7dff6400a38af8afefb317f8581a59b3"
language = " "
@app.route('/update_language', methods=['POST'])
def update_language():
    language = request.form.get('language')
    print(language)
    # session['language'] = language
    print("Language updated to:" , {language})
    return "UPDATED"
@app.route("/asr_upload", methods=["GET", "POST"])
def asr_upload():
            text = None
            # language = None
            f = request.files['file']
            f.save(f.filename)
            print(f.filename)
            f1 =f.filename.split('\\')
            file = f1[-1].split('.')[0]
            os.system("ch_wave " + f.filename + " -F 16000 -otype wav -o temp.wav")
            if language == 'English':
                headersList = {
                    "Authorization": f"Token {token}"
                    }
                files = {
                    'file': open('temp.wav', 'rb'),
                    'language': (None, 'english'),
                    'vtt': (None, 'true'),
                    }
                response = requests.post('https://asr.iitm.ac.in/api/asr/', files=files,
                                         headers=headersList)
                text = response.json().get("transcript")
                print(text)
            elif language == 'Tamil':
                        headersList = {
                            "Authorization": f"Token {token}"
                            }
                        files = {
                            'file': open('temp.wav', 'rb'),
                            'language': (None, 'tamil'),
                            'vtt': (None, 'true'),
                            }
                        response = requests.post('https://asr.iitm.ac.in/api/asr/', files=files,
                                                 headers=headersList)
                        text = response.json().get("transcript")
                        print(text)
            
            os.system("rm *.wav")
            return render_template('output_asr.html', transcript=text)
@app.route("/asr_record", methods=["GET", "POST"])
def asr_record():
        text = None
        # Recording parameters
        duration = 5  # seconds
        fs = 16000  # sample rate
        filename = 'temp.wav'

    # Record audio
        recording = sd.rec(int(duration * fs), samplerate=fs, channels=1, dtype=np.int16)
        sd.wait()
        print("recorded")
    # Save recorded audio to a file
        sf.write(filename, recording, fs)
        language = session.get('language')  # Default to 'English' if not set
        print(language)
        if language == 'English':
                headersList = {
                    "Authorization": f"Token {token}"
                    }
                files = {
                    'file': open('temp.wav', 'rb'),
                    'language': (None, 'english'),
                    'vtt': (None, 'true'),
                    }
                response = requests.post('https://asr.iitm.ac.in/api/asr/', files=files,
                                         headers=headersList)
                text = response.json().get("transcript")
                print(text)
        elif language == 'Tamil':
             headersList = {
                 "Authorization": f"Token {token}"
                 }
             files = {
                 'file': open('temp.wav', 'rb'),
                 'language': (None, 'tamil'),
                 'vtt': (None, 'true'),
                 }
             response = requests.post('https://asr.iitm.ac.in/api/asr/', files=files,
                                      headers=headersList)
             text = response.json().get("transcript")
             print(text)
                     
            
        os.system("rm *.wav")
        return render_template('output_asr.html', transcript=text)

if __name__ == '__main__':
    app.run(host='0.0.0.0')