#!/bin/tcsh -f

if($# != 2) then
        echo "arguments: wordlist dictionary"
        exit(-1)
endif
 
set i = 1
set tot = `cat $1 | wc -l`
while ($i <= $tot)

	set a = `cat $1 | head -$i | tail -1`
	echo $a $a  >> $2

@ i++
end
